#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
baseline.py

Reads an initial hyperparameter CSV (e.g., generated by NLHD),
evaluates all points using the U-Net training pipeline, 
and finds the best Validation Dice Score to establish a baseline.
"""

import argparse
import os
import pandas as pd
import time

# Import your existing U-Net training entry point
from train import run_training

def evaluate_baseline(
    csv_path: str,
    dataset: str,
    data_root: str,
    out_dir: str,
    seed: int = 42,
    epochs: int = 3,
    split_file: str | None = None,
):
    print(f"========== Starting Baseline Evaluation ==========")
    print(f"Dataset: {dataset}")
    print(f"Reading configs from: {csv_path}")
    print(f"Output directory: {out_dir}")
    print(f"================================================\n")

    os.makedirs(out_dir, exist_ok=True)
    
    # 1. Read the initial parameter table generated by NLHD
    df = pd.read_csv(csv_path)
    
    results = []
    best_overall_dice = -float('inf')
    best_config = None

    # 2. Iterate through each row in the parameter table
    for idx, row in df.iterrows():
        print(f"\n--- Running Config {idx + 1}/{len(df)} ---")
        
        # Extract hyperparameters of the current row (ensure column names match your CSV)
        lr = float(row['learning_rate'])
        bs = int(row['batch_size'])
        scale = float(row['img_scale'])
        val_pct = float(row['val_percent'])
        
        print(f"Params: LR={lr:.2e}, BatchSize={bs}, Scale={scale:.2f}, ValPercent={val_pct:.2f}")

        # Create a separate output directory for this current combination
        tag = f"run{idx:02d}_lr{lr:.6e}_bs{bs}_scale{scale:.2f}_val{val_pct:.2f}"
        trial_dir = os.path.join(out_dir, tag)
        os.makedirs(trial_dir, exist_ok=True)

       # 3. Construct arguments to pass to train.py
        args = argparse.Namespace(
            dataset=dataset,
            data_root=data_root,
            output_dir=trial_dir,
            split_file=split_file,
            epochs=epochs,            # Suggested to keep the number of epochs consistent with BO search
            batch_size=bs,
            lr=lr,
            img_scale=scale,
            val_percent=val_pct,
            amp=False,                 
            bilinear=False,
            classes=1,
            load="",
            save_checkpoint=False,    
            use_wandb=False,
            weight_decay=1e-8,
            momentum=0.999,
            gradient_clipping=1.0,
            num_workers=4,
            seed=seed,
            device="auto"
        )

        # 4. Run training and get results
        t0 = time.time()
        result_dict = run_training(args)
        elapsed = time.time() - t0
        
        val_dice = float(result_dict["best_val_dice"])
        print(f"Result for Config {idx + 1}: Val Dice = {val_dice:.4f} (took {elapsed/60:.1f} mins)")

        # Record results
        row_result = row.to_dict()
        row_result["val_dice"] = val_dice
        row_result["elapsed_sec"] = elapsed
        row_result["trial_dir"] = trial_dir
        results.append(row_result)

        # Update global best
        if val_dice > best_overall_dice:
            best_overall_dice = val_dice
            best_config = row_result

    # 5. Save summary results
    results_df = pd.DataFrame(results)
    summary_csv = os.path.join(out_dir, f"{dataset}_baseline_summary.csv")
    results_df.to_csv(summary_csv, index=False)
    
    print(f"\n========== Baseline Evaluation Complete ==========")
    print(f"Summary saved to: {summary_csv}")
    print(f"🌟 BEST BASELINE DICE: {best_overall_dice:.4f} 🌟")
    print(f"Best Config: LR={best_config['learning_rate']:.2e}, "
          f"BatchSize={int(best_config['batch_size'])}, "
          f"Scale={best_config['img_scale']:.2f}, "
          f"ValPercent={best_config['val_percent']:.2f}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv_path", type=str, required=True, help="Path to the initial init_df_...csv file")
    parser.add_argument("--dataset", type=str, required=True, choices=["carvana", "isic2018"])
    parser.add_argument("--data_root", type=str, required=True, help="Path to the dataset directory")
    parser.add_argument("--out_dir", type=str, default="./baseline_results", help="Directory to save baseline outputs")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--split_file", type=str, default=None,
                    help="Fixed split json shared by baseline and BO")
    parser.add_argument("--epochs", type=int, default=3, help="Number of epochs per run (should match BO)")
    
    args = parser.parse_args()
    
    evaluate_baseline(
        csv_path=args.csv_path,
        dataset=args.dataset,
        data_root=args.data_root,
        out_dir=args.out_dir,
        seed=args.seed,
        epochs=args.epochs,
        split_file=args.split_file,
    )

if __name__ == "__main__":
    main()